name: Node CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: make install
    - run: make test
    - run: make lint
    - name: code coverage 
      uses:  paambaati/codeclimate-action@v2.5.7
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
          coverageCommand: make test-coverage
          debug: true
